Component Library for Google Calendar (#1)
initial components

diff --git a/.github/workflows/run-workflow-tests.yml b/.github/workflows/run-workflow-tests.yml
--- a/.github/workflows/run-workflow-tests.yml
+++ b/.github/workflows/run-workflow-tests.yml
@@ -16,13 +16,16 @@ jobs:
         python-version: ["3.9", "3.10", "3.11"]
     env:
       TEST_XIRCUITS: |
-        example.xircuits
+        examples/check_event.xircuits
+      SERVICE_JSON_PATH: ${{ secrets.SERVICE_JSON_PATH }}
+      CALENDAR_ID: ${{ secrets.CALENDAR_ID }}
+
     steps:
     - name: Checkout Repository
-      uses: actions/checkout@v4
+      uses: actions/checkout@v3
 
     - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v5
+      uses: actions/setup-python@v4
       with:
         python-version: ${{ matrix.python-version }}
 
@@ -47,7 +50,7 @@ jobs:
         fi
 
     - name: List Xircuits
-      run: xircuits list 
+      run: xircuits list
 
     - name: Clone Repository
       run: |
@@ -61,6 +64,8 @@ jobs:
 
     - name: Install Component Library
       run: |
+        echo "Installing pyOpenSSL specific version..."
+        pip install pyOpenSSL==24.2.1
         if [ -f "${{ env.COMPONENT_LIBRARY_PATH }}/requirements.txt" ]; then
           echo "requirements.txt found, installing dependencies..."
           pip install -r ${{ env.COMPONENT_LIBRARY_PATH }}/requirements.txt
@@ -70,45 +75,49 @@ jobs:
 
     - name: Test .xircuits Workflows
       run: |
-        export PYTHONPATH="${GITHUB_WORKSPACE}:${PYTHONPATH}"
-        LOG_FILE="${GITHUB_WORKSPACE}/workflow_logs.txt"
-        TEST_FILES=$(echo "$TEST_XIRCUITS" | tr '\n' ' ')
-        echo "Repository: $LIBRARY_NAME" > $LOG_FILE
-        echo "Branch: $BRANCH_NAME" >> $LOG_FILE
-        echo -e "Testing Files:\n$TEST_FILES" >> $LOG_FILE
-        IFS=' ' read -r -a FILE_ARRAY <<< "$TEST_FILES"
-        FAIL=0
-        if [ ${#FILE_ARRAY[@]} -eq 0 ]; then
-          echo "No .xircuits files specified for testing." | tee -a $LOG_FILE
-        else
-          for file in "${FILE_ARRAY[@]}"; do
-            FULL_PATH="${COMPONENT_LIBRARY_PATH}/${file}"
-            if [ -f "$FULL_PATH" ]; then
-              WORKFLOW_LOG_FILE="${FULL_PATH%.*}_workflow_log.txt"
-              echo -e "\n\nProcessing $FULL_PATH..." | tee -a $LOG_FILE
-              xircuits compile $FULL_PATH "${FULL_PATH%.*}.py" 2>&1 | tee -a $LOG_FILE
-              python "${FULL_PATH%.*}.py" 2>&1 | tee -a $WORKFLOW_LOG_FILE
-              LAST_LINE=$(tail -n 1 "$WORKFLOW_LOG_FILE")
-              if [[ "$LAST_LINE" != "Finished Executing" ]]; then
-                echo "Error: Workflow $FULL_PATH did not finish as expected" | tee -a $LOG_FILE
-                FAIL=1
+          export PYTHONPATH="${GITHUB_WORKSPACE}:${PYTHONPATH}"
+          LOG_FILE="${GITHUB_WORKSPACE}/workflow_logs.txt"
+          TEST_FILES=$(echo "$TEST_XIRCUITS" | tr '\n' ' ')
+          echo "Repository: $LIBRARY_NAME" > $LOG_FILE
+          echo "Branch: $BRANCH_NAME" >> $LOG_FILE
+          
+          # Decode the Base64 encoded JSON and save it to a file
+          echo "${{ secrets.SERVICE_JSON_PATH }}" | base64 -d > service_account.json
+     
+          echo -e "Testing Files:\n$TEST_FILES" >> $LOG_FILE
+          IFS=' ' read -r -a FILE_ARRAY <<< "$TEST_FILES"
+          FAIL=0
+          if [ ${#FILE_ARRAY[@]} -eq 0 ]; then
+            echo "No .xircuits files specified for testing." | tee -a $LOG_FILE
+          else
+            for file in "${FILE_ARRAY[@]}"; do
+              FULL_PATH="${COMPONENT_LIBRARY_PATH}/${file}"
+              if [ -f "$FULL_PATH" ]; then
+                WORKFLOW_LOG_FILE="${FULL_PATH%.*}_workflow_log.txt"
+                echo -e "\n\nProcessing $FULL_PATH..." | tee -a $LOG_FILE
+                xircuits compile $FULL_PATH "${FULL_PATH%.*}.py" 2>&1 | tee -a $LOG_FILE
+                python "${FULL_PATH%.*}.py" --service_json_path "service_account.json" --calendar_id "$CALENDAR_ID" 2>&1 | tee -a $WORKFLOW_LOG_FILE
+                LAST_LINE=$(tail -n 1 "$WORKFLOW_LOG_FILE")
+                if [[ "$LAST_LINE" != "Finished Executing" ]]; then
+                  echo "Error: Workflow $FULL_PATH did not finish as expected" | tee -a $LOG_FILE
+                  FAIL=1
+                else
+                  echo "$FULL_PATH processed successfully" | tee -a $LOG_FILE
+                fi
+                cat "$WORKFLOW_LOG_FILE" | tee -a $LOG_FILE
               else
-                echo "$FULL_PATH processed successfully" | tee -a $LOG_FILE
+                echo "Specified file $FULL_PATH does not exist" | tee -a $LOG_FILE
+                FAIL=1
               fi
-              cat "$WORKFLOW_LOG_FILE" | tee -a $LOG_FILE
-            else
-              echo "Specified file $FULL_PATH does not exist" | tee -a $LOG_FILE
-              FAIL=1
-            fi
-          done
-        fi
-        if [ $FAIL -ne 0 ]; then
-          echo "One or more workflows failed or did not finish as expected." | tee -a $LOG_FILE
-          exit 1
-        else 
-          echo "Workflow processing completed" | tee -a $LOG_FILE
-        fi
-
+            done
+          fi
+          if [ $FAIL -ne 0 ]; then
+            echo "One or more workflows failed or did not finish as expected." | tee -a $LOG_FILE
+            exit 1
+          else 
+            echo "Workflow processing completed" | tee -a $LOG_FILE
+          fi
+     
     - name: Upload log file
       if: always()
       uses: actions/upload-artifact@v4
